### ISSUE TITLE
Data movie was created

### ISSUE THREAD

**Issue by cinjon** [Zulko/moviepy#1021]
Love the library - been using it for a lot of utilities. Is it possible to use Moviepy to get the video information like when/where the movie was made?

**Comment by tburrows13** [comment]
This isn't currently possible within moviepy. A quick google search shows a few resources which may help:
https://gist.github.com/oldo/dc7ee7f28851922cca09
https://github.com/Zulko/moviepy/issues/249

Let us know if you'd be interested in adding this yourself!

**Comment by mondeja** [comment]
After #1466, this is now possible with the version in the **master** branch (not released in PyPI yet):

```python
from pprint import pprint
from moviepy.video.io.ffmpeg_reader import ffmpeg_parse_infos

video_data = ffmpeg_parse_infos("path/to/your/video/file.ext")
pprint(video_data)
```

Keep in mind that the field to check for retrieve this information will depend on the file type, because each container stores metadata differently. See [this](https://wiki.multimedia.cx/index.php?title=FFmpeg_Metadata) for more information.
