### ISSUE TITLE
Concatenation does not correctly work out new clip's duration

### ISSUE THREAD

**Issue by BboyHanat** [Zulko/moviepy#1045]
I got a error when I iteration the clip frames(clip.iter_frames()) after concatnated two clips, and I check the totally frames count, it got a wrong frames count,  and I check your code, find some dubious code.
I think the concatnated clip duration  is can't just sum the clips duration, because you set the  concatnated clip fps by max(clips.fps),  I have try this equation(it's worked on my code):

     clip_total.duration = (clip1.fps * clip1.duration)/ max_fps + (clip2.fps * clip2.duration)/max_fps

Or you can find some solution to  solve this problem.
My envirment info:
  - Python Version: 3.7
  - Moviepy Version: 1.0.1
  - Platform Name: macOS
  - Platform Version:  10.14.4

**Comment by tburrows13** [comment]
See #796 - related but probably not the same issue. From a cursory inspection of `concatenate_videoclips` I can't see how this would be an issue, but maybe someone else would like to properly investigate + fix it?

**Comment by jcbrockschmidt** [comment]
I believe the expected behavior does of this issues does not align with the expected behavior of the spec. For illustrative purposes, here's an equivalent re-write of the above equation:
```python
number_of_frames_1 = clip1.fps * clip1.duration
number_of_frames_2 = clip2.fps * clip2.duration
clip_total.duration = number_of_frames_1 / max_fps + number_of_frames_2 / max_fps
```
The equation provided appears to suggest that composing frames with two different FPS ought to result in a clip with no additional frames, which (as far as I can tell) is not intended behavior.

Suppose `clip1` has an FPS of 60, and `clip2` has an FPS of 30. According to the spec for `concatenate_videoclips`, "The clip with the highest FPS will be the FPS of the result clip". So `clip_total` will have 60 FPS. If we wanted to adjust `clip2` to be 60 FPS without removing any frames, it would have to playback at twice the speed. In this scenario, the proposed duration calculation would work.

But what `MoviePy` does instead is copy each frames of `clip2` to maintain its duration. That's what happens with this code:
```python
from moviepy.editor import *

a = ColorClip((640, 480), color=(255, 0, 0)).set_fps(30).set_duration(3)
b = ColorClip((1080, 960), color=(0, 255, 0)).set_fps(60).set_duration(5)
print("total duration:", a.duration + b.duration)
print("a frames:", len(list(a.iter_frames())))
print("b frames:", len(list(b.iter_frames())))
print()

composed = concatenate_videoclips([a, b], method="compose")
print("composed duration:", composed.duration)
print("composed frames:", len(list(composed.iter_frames())))
print()

chained = concatenate_videoclips([a, b], method="chain")
print("chained duration:", chained.duration)
print("chained frames:", len(list(chained.iter_frames())))
```
The output being
```
total duration: 8
a frames: 90
b frames: 300

composed duration: 8
composed frames: 480

chained duration: 8
chained frames: 480

```
Notice that the duration of both concatenated clips is the sum of `a.duration` and `b.duration`, but the frame counts are greater than the sum of the frames from `a` and `b`. From what I understand, this is what is supposed to happen.

@BboyHanat let me know whether I'm understanding your problem or not. If I am misunderstanding, it would help if you would provide some example code to demonstrate how you got a video clip with the wrong duration / frame count.

* Python Version: 3.7.9
* Moviepy Version: 1.0.1
* Platform Name: Ubuntu
* Platform Version: 20.04.1

**Comment by mondeja** [comment]
Great explanation @jcbrockschmidt.

To solve the issue you could use the parameter `change_duration` to halve the clip duration with less fps. Consider these examples:

```python
clip1 = ColorClip(color=(255, 0, 0), size=(1, 1)).with_duration(1).with_fps(1)
clip2 = ColorClip(color=(0, 0, 255), size=(1, 1)).with_duration(1).with_fps(2)
final_clip1 = concatenate_videoclips([clip1, clip2])
for frame in final_clip1.iter_frames():
    print(frame)
"""OUTPUT:

[[[255   0   0]]]
[[[255   0   0]]]
[[[  0   0 255]]]
[[[  0   0 255]]]
"""
```

```python
clip3 = ColorClip(color=(255, 0, 0), size=(1, 1)).with_duration(1).with_fps(1).with_fps(2, change_duration=2)
clip4 = ColorClip(color=(0, 0, 255), size=(1, 1)).with_duration(1).with_fps(2)
final_clip2 = concatenate_videoclips([clip3, clip4])
for frame in final_clip2.iter_frames():
    print(frame)

"""OUTPUT:
[[[255   0   0]]]
[[[  0   0 255]]]
[[[  0   0 255]]]
"""
```

In the first example, the number of frames of the first clip red are two (R: 255, G: 0, B: 0) with the clip originally having 1 fps and 1 second. In the second, the clip keeps their original number of frames because the speed has been multiplied by two.

So if you want to maintain the number of frames as the original in a concatenated clip, probably you can use something like this:

```python
max_fps = max(clip.fps for clip in clips)
clip.with_fps(max_fps, change_duration=max_fps / clip.duration)
```

Python Version: 3.8.5
Moviepy Version: master
Platform Name: Ubuntu
Platform Version: 20.04.01
