### ISSUE TITLE
Drop support for python < 3.6

### ISSUE THREAD

**Issue by mgaitan** [Zulko/moviepy#1081]
I've been working in a couple of refactors and I feel it's time to stop supporting both python 2.7 and python 3.5, and ensure support to python 3.7 (see #1018), 3.8 and any new python release in the future. 

As you may know, python2.7 reaches its end-of-life date starting 2020, and 3.5's one is the next september. Several of the most relevant libraries of the python ecosystem (e.g, django and numpy, just to mention few) are already python3 only since a while. 

This would simplify the code and the tests a bit (not a big deal, to be sincere), but most importantly, it'll allow us to start using new idioms/features of the language without hacks, conditional requirements, etc.

**Comment by Zulko** [comment]
I am in favor. Anyone against?

**Comment by tburrows13** [comment]
According to `pypinfo`, 10% of downloads in the last 30 days from PyPI are on Python 2. On https://pypistats.org/packages/moviepy it hovers at around 20% (same source data as `pypinfo`, so probably just because of those massive spikes).

I agree that it is worth doing. Python 3.5 I'm not so sure if the tiny benefits outweigh the decreased support. I don't really mind though.

For completeness, here are some PyPI stats from the last 30 days:

| version   | percent | download_count |
| --------- | ------- | -------------- |
| 1.0.1     |  73.94% |        146,036 |
| 0.2.3.2   |  13.82% |         27,296 |
| 1.0.0     |   5.31% |         10,481 |
| 0.2.2.11  |   4.83% |          9,538 |
| 0.2.3.5   |   1.70% |          3,359 |
| 0.2.2.13  |   0.20% |            393 |
| 0.2.3.4   |   0.07% |            132 |
| 0.2.3.1   |   0.06% |            125 |
| 0.2.1.6.3 |   0.04% |             75 |
| 0.2.3.3   |   0.04% |             71 |


| python_version | percent | download_count |
| -------------- | ------- | -------------- |
| 3.6            |  63.88% |        127,917 |
| 3.7            |  11.74% |         23,507 |
| 2.7            |  10.84% |         21,699 |
| None           |   6.01% |         12,041 |
| 3.5            |   3.95% |          7,906 |
| 3.8            |   3.50% |          7,002 |
| 3.4            |   0.07% |            148 |
| 3.9            |   0.01% |             16 |
| 2.6            |   0.00% |              2 |
| 3.2            |   0.00% |              1 |


| system_name          | percent | download_count |
| -------------------- | ------- | -------------- |
| Linux                |  84.28% |        168,762 |
| None                 |   8.92% |         17,857 |
| Windows              |   5.00% |         10,011 |
| Darwin               |   1.80% |          3,598 |
| FreeBSD              |   0.00% |              2 |
| OpenBSD              |   0.00% |              2 |
| MSYS_NT-10.0-18363   |   0.00% |              1 |
| CYGWIN_NT-10.0-18362 |   0.00% |              1 |
| MSYS_NT-10.0         |   0.00% |              1 |
| CYGWIN_NT-10.0-WOW   |   0.00% |              1 |

**Comment by keikoro** [comment]
Sounds good to me.

**Comment by tburrows13** [comment]
With the merging of #1106, this PR can now be closed.
