### ISSUE TITLE
Add a selection of Github apps

### ISSUE THREAD

**Issue by tburrows13** [Zulko/moviepy#1092]
@Zulko I'd like to suggest adding a few GitHub App integrations to make managing the project a little easier.

All you need to do is install the ones that you're happy with; I can then create the relevant config files in .github and set them up.

Here's the ones that I think would be useful

- https://probot.github.io/apps/mergeable/ (prevent merging unless it has certain labels that the release drafter can categorise it with)
- ~https://probot.github.io/apps/release-drafter/~
- https://probot.github.io/apps/polls/ (could be useful at some point; see demo [here](https://github.com/evenchange4/gh-polls-bot/issues/2))
- https://probot.github.io/apps/no-response/ (it can auto close issues with the label 'awaiting-response' after a few weeks of inactivity)
- https://probot.github.io/apps/ci-reporter/ (maybe...? it might make things unnecessarily cluttered)
- ~https://probot.github.io/apps/stale/ (automatic marking stale, then later closing of inactive issues/PRs. I'm not sure if this would be a good idea, it might be a bit heavy handed, up to discussion)~

Thanks to @keikoro on Gitter for suggesting these!

**Comment by keikoro** [comment]
I think I found the above mentioned https://probot.github.io/apps/no-response/ interesting as well, just didn't suggest it because it does require labelling new issues first, which is something we don't do regularly enough, ha. I myself also only get to in bursts.

I do like your additional suggestions.

**Comment by keikoro** [comment]
Relatedly, though not quite on topic for this issue: I'll try to go through our labels sometime soon to better group them together, or clarify their meanings etc.

Actually, I should probably open a separate issue with my suggestions, so I can get input by everyone else. (I think this just hasn't come up so far because I took the initiative on creating the first big batch of labels just so I could get some sort of order into the issues.)

**Comment by tburrows13** [comment]
I went through the list of labels yesterday to try and streamline them somewhat: https://github.com/Zulko/moviepy/labels

More input would always be appreciated. There's also the (mostly defunct) label wiki: https://github.com/Zulko/moviepy/wiki/Label-Wiki

I'm still a fan of the first section ("All PRs must have one of these") which makes it a lot easier to generate a meaningful changelog. Using the Mergable GitHub app, we'd be able to enforce this.

**Comment by keikoro** [comment]
Yeah, I think you using new labels and me doing the very same for a work project atm (including doing reading up again on the topic and looking up how others do it) is what made me think I should contribute to updating them as well.

There's overlap in new ones and ones I created (but perhaps should have named better), and cleaning up the colours and not relying on those (alone) for grouping labels but using prefixes as well might make sense.

Will open an issue but it'll probably have to wait until the weekend!

**Comment by keikoro** [comment]
Ohh, and thanks for linking to the wiki page, it seems that one passed me by, oops.

**Comment by tburrows13** [comment]
I think I made the wiki before there was option to add description directly to the tags (or I didn’t know about it). I think just using the descriptions is much easier and prevents keeping around outdated information.

**Comment by tburrows13** [comment]
With hindsight, imo none of these are actually necessary.
