### ISSUE TITLE
tmp file can't be deleted while using TextClip()

### ISSUE THREAD

**Issue by cqzhao** [Zulko/moviepy#110]
When I use TextClip():

```
txt_clip = TextClip("This is a test for txtclip!",fontsize=30,color='white')
txt_clip =  txt_clip.set_pos('center','bottom').set_duration(15)
clip.subclip(10,25)

video = CompositeVideoClip([clip.subclip(10,25),txt_clip])
video.write_videofile("test.mp4",fps=clip.fps)
```

there will be an error:
```
os.remove(tempfilename)
WindowsError: [Error 32] : 'c:\users\legend\appdata\local\temp\tmpbg_kkw.p
ng'
```
The temp file is not closed before it will be removed. Add remove_temp=False as parameter will solve this,but it's better to close and remove it. what should I do?

**Comment by carlodri** [comment]
I have the same issue with Win8x64, Python 3.4, moviepy 0.2.1.9.2.

If I say 
```python
TextClip("hello", tempfilename = "test.png")
```

I get:

```
   1151         if remove_temp:
   1152             if os.path.exists(tempfilename):
-> 1153                 os.remove(tempfilename)
   1154             if os.path.exists(temptxt):
   1155                 os.remove(temptxt)

PermissionError: [WinError 32] The process cannot access the file because it is
being used by another process: 'test.png'
```

@zulko: I have tried to investigate the problem briefly, but I cannot find the culprit...

**Comment by Zulko** [comment]
I just changed the way images are read in MoviePy (now it's through ImageIO), and I have great hopes that this solved your bug. Could you try to upgrade and tell me if it works now ?

**Comment by carlodri** [comment]
@Zulko, it works now, thanks! The above command returns no error on my system.

**Comment by thechickensage** [comment]
I get the same error on the os.remove(tempfilename).  I'm using a miniconda-installed python 3.4 64-bit on Windows 7, and my moviepy installation is moviepy-0.2.2.4.  The first tempfilename was something like txywqyyysgajo.png, but i added in the tempfilename kwarg to the call to TextClip:

txtClip = TextClip('Cool effect',color='white', font="Amiri-Bold",
                   kerning = 5, fontsize=100, tempfilename='test1.png')

In Eclipse, the traceback:
Traceback (most recent call last):
  File "E:\programming\anim\src\test.py", line 9, in <module>
    kerning = 5, fontsize=100, tempfilename=r'test1.png')
  File "C:\Miniconda3\lib\site-packages\moviepy-0.2.2.4-py3.4.egg\moviepy\video\VideoClip.py", line 1153, in __init__
    os.remove(tempfilename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'test1.png'

I'm not really sure where to start figuring this out.

**Comment by keikoro** [comment]
Closing this due to lack of response after a potential solution was proposed.
(The original questions seem to have received sufficient answers.)
