### ISSUE TITLE
What is the meaning of 'fl'?

### ISSUE THREAD

**Issue by tburrows13** [Zulko/moviepy#1125]
`fl` appears all over the source code, however I've never known what it actually means. Is it 'filter', or something else? Would it be possible to change the function names to something more explicit?

**Comment by Zulko** [comment]
``fl`` means filter and I am sorry (moviepy was my first ambitious API). I could be replaced by "filter", but if you go down the route of changing API names for v2, I'd suggest a complete rethink. One of the most confusing things with moviepy is that is uses ``fl``, ``set_duration``, ``set_start``, while these methods are not in-place. A clearer interface would be ``with_duration``, etc. so that a typical code would read:

```
new_clip = clip.with_duration(5).with_filter(black_and_white)
```

**Comment by tburrows13** [comment]
I'd support renaming all such methods in v2.0. @mgaitan thoughts?
And we'd have to decide whether to deprecate or fully remove the old ones.

**Comment by tburrows13** [comment]
Closing as `fl` has been replaced with `transform` in v2.0 now.
