### ISSUE TITLE
Write text on Video

### ISSUE THREAD

**Issue by Raamyy** [Zulko/moviepy#1127]
Is it possible to use moviepy to write text on a video ?

**Comment by tburrows13** [comment]
Yes it is! Use a [TextClip](https://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html#textclip). This will require installing ImageMagick: https://zulko.github.io/moviepy/install.html#other-optional-but-useful-dependencies
Let us know if you have other queries.

**Comment by Raamyy** [comment]
@tburrows13 Thanks for your response !

I think there is no example of usage in the documentation to get more info on how to do it.

But in a brief i need to write subtitles on the video (i need them to be rendered on the clip). So i have a list of text each element has a string containing the text and the start, end of the subtitles to be shown on the clip.

I can't get how can I write the text in a certain interval of time.

**Comment by tburrows13** [comment]
Admittedly the documentation is not great, but quite a few of the example scripts use TextClips eg https://zulko.github.io/moviepy/examples/ukulele_concerto.html.

However, for your needs, there is actually a dedicated [SubtitlesClip](https://zulko.github.io/moviepy/ref/videotools.html#module-moviepy.video.tools.subtitles). If your subtitle file looks like https://github.com/Zulko/moviepy/blob/master/media/subtitles1.srt then the SubtitlesClip will be very easy to use, just use the example in the docs (I think that it is missing a `from moviepy.video.compositing.CompositeVideoClip import CompositeVideoClip` line though).

**Comment by Raamyy** [comment]
Thanks that will help

Actually the subtitles are on **VTT format** not SRT.
VTT is the subtitles format used by **HTML Video players**. It is very close to the SRT format

![image](https://user-images.githubusercontent.com/29176293/78378174-e7c02c80-75d0-11ea-9b1d-32c982a4fe0c.png)
![image](https://user-images.githubusercontent.com/29176293/78378226-f9093900-75d0-11ea-82c0-0aeac86adf44.png)

I think having a  .VTT Parser in **_moviepy_** will be a great Plus !

**Comment by mgaitan** [comment]
@Raamyy you should try convert your subtitles file in advance to the supported format. 
You even could do it with python using this library
https://pycaption.readthedocs.io/en/stable/

Maybe we could optionally support different subtitles formats using that library in moviepy, but for sure, to have a dedicate parser in the library doesn't seem a great idea because it requires tests, and maintain and then another user would like to support another format, and so on. 

If there is another well maintained tool to do it _in python_ it's easier you use that.

**Comment by Raamyy** [comment]
@mgaitan I wrote my own parser. Thanks for your response !
