### ISSUE TITLE
`change_end=False` in `set_duration()` method does not work

### ISSUE THREAD

**Issue by spfeifer222** [Zulko/moviepy#1166]
```python
from moviepy.editor import VideoFileClip, AudioFileClip

audio1 = AudioFileClip('file.mp4') 
audio1_test = audio1.set_duration(t="00:03:35.00", change_end=False)
audio1_test.duration  # note: output confirms correct length: 215.0
audio1_test.to_audiofile('audio1_test_short.mp3') 
# alternatively tested: 
audio1_test.write_audiofile('audio1_test_short.mp3') 

```
### Expected Behavior
audio1_test_short.mp3 contains the end of the audio1 file (215 sec.) 

### Actual Behavior
audio1_test_short.mp3 contains the beginning of the audio1 file (215 sec.)

### Steps to Reproduce the Problem
see code above

### Specifications

  - Python Version: 3.8.2
  - Moviepy Version: 1.0.2
  - Platform Name: Linux Mint Mate 
  - Platform Version: 19.3

**Comment by tburrows13** [comment]
Hello! You're problem is that `set_duration` is setting `audio1_test.end` attribute correctly, however, that attribute is only used when a `CompositeVideoClip` is created from the clip.

In your case, instead of using `.set_duration`, use `.subclip()`, which actually changes the clip (as well as sorting out duration values, it uses `self.fl_time(lambda t: t + t_start`).

For example, you could use `audio1_test = audio1.subclip(t="00:-03:-35.00")`. Notice the negatives in the string: subclip supports negative times in the same way that lists support negative index slices, so it counts from the end instead. Your time string is passed to `tools.cvsecs`, which does appear to return a negative from a string representation if each item in it is set to negative. Not ideal, I know.

**Comment by spfeifer222** [comment]
Hey, thank you for your quick reply!

Yesterday, I had a closer look to the code and found how times are handled by `tools.cvsecs`. I was able to manage that by using `subclip()`, but this only was a part of my problem. However, this belings to another question and therefore, I will open a new thread to ask.

**Comment by tburrows13** [comment]
Great!
