### ISSUE TITLE
Unspecified Imagemagick binary in GitHub actions

### ISSUE THREAD

**Issue by filiptronicek** [Zulko/moviepy#1204]
I wanted to setup moviepy as a small experiment on GitHub actions, but I stumbled upon a problem with moviepy locating the binary.
![image](https://user-images.githubusercontent.com/29888641/83268651-37cd0100-a1c6-11ea-8776-03852b02d1ed.png)

Although it's a part of the preinstalled suite of dependencies and programs on GitHub's Ubuntu distribution (complete list [here](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md)). moviepy cannot locate it.
Is this a GitHub or a moviepy problem?
#### Expected Behavior
The program renders the video just fine (tested on my Windows 10 PC.)

#### Actual Behavior
![image](https://user-images.githubusercontent.com/29888641/83268450-f0467500-a1c5-11ea-8434-986f5877101e.png)

#### Specifications

  - Python Version: 3.8
  - Moviepy Version: 1.0.3
  - Platform Name: Ubuntu Linux 
  - Platform Version: 18.04.4 LTS

**Comment by tburrows13** [comment]
That error message is just a generic one for when ImageMagick fails. The other 2 lines indicate that it can find ImageMagick, but it is failing due to https://github.com/Zulko/moviepy/issues/693#issuecomment-355587113.

You can add the following line into your install script to fix it:

      cat /etc/ImageMagick-6/policy.xml | sed 's/none/read,write/g' | sudo tee /etc/ImageMagick-6/policy.xml

I suppose that you might need to replace `6` with `7`.

**Comment by filiptronicek** [comment]
That did the trick! Thanks! Works just fine with version six.
