### ISSUE TITLE
Optimize speed and textclip problems

### ISSUE THREAD

**Issue by OrcAniCe** [Zulko/moviepy#1216]
```
def create_video_of_list_of_clips(clips, output):
    final_clips = []
    intro = VideoFileClip("intro.mp4", target_resolution=(1080, None))
    final_clips.append(intro)

    for clip in clips:
        path = constants.DOWNLOAD_LOCATION + clip.channel.slug + '/' + clip.slug + '.mp4'

        video = VideoFileClip(path)
        title = TextClip(txt=clip.title, font='Amiri-regular', color='white', fontsize=70, stroke_color='black', stroke_width=1).set_duration(10).set_pos((15, 790))
        title2 = TextClip(txt=clip.channel.name, font='Amiri-regular', color='white', fontsize=30, stroke_color='black', stroke_width=1).set_duration(10).set_pos((15, 890))

        final_clip = CompositeVideoClip([video.crossfadein(1), title, title2]).resize( (1920,1080) )
        final_clips.append(final_clip)

    finished = concatenate_videoclips(final_clips, method='compose')
    finished.write_videofile(output, preset='superfast', threads=4)
```

I'm trying to figure out if there's a way to optimize the speed of my code. a 5-7 min video takes between 2.5-3 hours to render. 

also, I'm struggling to figure out how the position par works. after what I understand then the first text should be 15 pixels <--- away from here. and 790 pixels away from the top. either I have totally misunderstood how it should work or I did something wrong in the code. 

**Specs**
CPU: Xeon E5-2630 v4 - 8 core
RAM: 30GB

Python 3.7.3
MoviePy 1.0.0

**Comment by tburrows13** [comment]
Regarding speed, I think that if you remove `method="compose"` it will go faster. I don't think that it will change the output file because all your clips are the same size anyway. The reason I say that is because a big performance hit is using nested CompositeVideoClips, and `method="compose"` creates a CompositeVideoClip internally. In v2.0, there is likely to be some performance improvements (see #1157 for more information).

I'm not sure what your issue is with `set_position()`? `.set_position((15, 790))` should set the top-right of the TextClip to 15 pixels from the left and 790 from the top. If it is not, then it is presumably a bug, or it may be that the top-right of the clip is not where you think it is.

**Comment by AndreasElkjaer** [comment]
Thanks for the tip. I'm gonna look into it :)

**Comment by keikoro** [comment]
@OrcAniCe Did you manage to look into this? Did the above suggestions help?

**Comment by keikoro** [comment]
Closing this due to lack of response after a potential solution was proposed.
