### ISSUE TITLE
Preview 1080p 60FPS will be very slow

### ISSUE THREAD

**Issue by Boliang-Lu** [Zulko/moviepy#1238]

**Comment by tburrows13** [comment]
Hello, this is because it must generate each frame in order to preview it. This is not generally possible to do in real time (and it is why it often takes longer to output a clip to a file than the length of the clip. See https://zulko.github.io/moviepy/getting_started/efficient_moviepy.html#clip-show-and-clip-preview for more information.

**Comment by Boliang-Lu** [comment]
thanks,I try run on new desktop that CPU is 3600x and GPU is gtx1650,   but CPU and GPU is low use, how can i imporve it？
