### ISSUE TITLE
Concanate clips with different size

### ISSUE THREAD

**Issue by omershelef** [Zulko/moviepy#124]
I tried to concanate multiple imageclips of different sizes into one video clip.
What happend is that the final clip was in the size of the first image clip (that was the size passed to the ffmpeg writer). This behavior caused that all clips which were not the same size ad the first one is ruined. Did i used the chain method wrong somehow?

**Comment by Zulko** [comment]
The method "chain" is a fast method but it doesn't work when you write directly the concatenation to a file because the resulting clip doesn't have a fixed size. Use method='compose' in in concatenate_videoclips, this will paint all the clips on a big canvas, and you will be able to write it in a videofile.

**Comment by kerstin** [comment]
I'm assuming the proposed solution worked > closing.
