### ISSUE TITLE
Why write_videofile() param 'threads=' does not work on windows? 

### ISSUE THREAD

**Issue by mike592** [Zulko/moviepy#1243]
Why write_videofile() param 'threads=' does not work on windows? I tested this code on a 48 cores windows server:

```
ThreadCount = multiprocessing.cpu_count()
bk_clip.write_videofile(output_file_name, fps=VideoFps, audio=False, logger=None, threads=ThreadCount)
```

There are only 3 ffmpeg.exe appears in the task list as below

![1111](https://user-images.githubusercontent.com/47173469/85226834-244f3780-b40c-11ea-8806-82af74010a28.png)

But this server is Intel Xeon E5-2678 v3 @ 2.50GHz,  2cpu * 12 cores = 24 cores.

It supposed to be 24 threads, but I only found 3 ffmpeg.exe

**Comment by tburrows13** [comment]
Hello, thanks for the question. First of all, is `multiprocessing.cpu_count()` definitely reporting a sensible number like 48?
Even then, the `threads` parameter is simply passed straight to FFmpeg so it becomes `-threads 48` there. I don't think that I can really help you with that because that is an FFmpeg issue.

**Comment by mike592** [comment]
![1111](https://user-images.githubusercontent.com/47173469/85227367-9f661d00-b40f-11ea-9c2a-8b87ad70e314.png)
I tested and cpu number is 32. and this time I found 4 ffmpeg.exe

**Comment by tburrows13** [comment]
I'm not sure that there is much that can be done. As it stands currently, all the frame transformations are done in single-threaded Python, so that may be your bottleneck currently. What sort of things are you doing with your clips. Make sure to avoid nested CompositeVideoClips because they are known to have a large performance penalty. #1157 also improves the performance of CompositeVideoClips (and will likely be in v2.0). You may also be interested in checking out #698, which implements multithreading into MoviePy. It is something that I would like to look at at some point, but it will require some work to ensure that it works correctly and reliably for general release, so unless someone else takes over #698, I don't see it being included before v2.1.

**Comment by mike592** [comment]
Thank you so much for your suggestion! But I am not sure what is 'nested CompositeVideoClips', could you drop me 2 or 3 lines code as an example of 'nested CompositeVideoClips'?

**Comment by tburrows13** [comment]
Sure, a nested CompositeVideoClip is a CompositeVideoClip of a CompositeVideoClip. Example:

```
# clip1, clip2, clip3, clip4 are all clips of some sort
composite1 = CompositeVideoClip([clip1, clip2], ...)
composite2 = CompositeVideoClip([clip3, clip4], ...)

nested_composite = CompositeVideoClip([composite1, composite2], ...)
```

**Comment by mike592** [comment]
But because all jobs are done only when write to a file. If we do some complex video editing works, there are always nested composite exists. How can we avoid this?  What I can do I is write to disk after every composite, am I right?

**Comment by tburrows13** [comment]
Yes, you could experiment with that and see if that would be faster. It might not be though, because it also takes a long time to write each clip to disk.

**Comment by mike592** [comment]
One of the key point of moviepy is the speed.  When will you think the new version moviepy can get the speed faster

**Comment by tburrows13** [comment]
I agree that I would love to have an improved speed in MoviePy.
Unfortunately, MoviePy is very limited by the number of active contributors (at the moment, only me). For the time being, I am working on changes that increase the usability and stability (both of which have been lacking for some time), which I think are more important at the moment, because once improved, they should reduce the 'community' work, such as handling bug reports and questions. It also makes it easier to add new features in the future if the existing code is stable.

For improving performance, there are the following things to take into account:
- Video processing is inherently slow because it will can only run on the CPU
- Python is inherently slow
- Multi-threading should speed it up, but I only have a dual-core laptop for development so it will be hard for me to analyse performance improvements.

I can't give a timeline, because (assuming that it is me that is still managing it), it entirely depends on how much time I am willing to give to this project, which depends on how much I am enjoying it.
Sorry.

Like I said earlier, if someone else who really priorities speed comes and works on that, then I'd be happy to review and merge that code (which is what happened in #1157 - will be merged soon).

**Comment by mike592** [comment]
I am really appreciated your excellent job, your job does make sense and important for a lot of people definitly

**Comment by jmoraispk** [comment]
I just want to leave a 'Thank you' note here. Although it is somewhat slow, it is far more practical than anything else I've tried. The time it takes rendering has far been compensated by the time it saves to code. And rendering does not require effort!
So, thank you @tburrows13 for all the work.
