### ISSUE TITLE
Maintenance application.

### ISSUE THREAD

**Issue by Gicehajunior** [Zulko/moviepy#1319]
Hello, Concerning the need for maintenances for this software, I hereby request for a chance to contribute and maintain it.

I will be glad if the chance is given to me.

Thankyou.

**Comment by tburrows13** [comment]
Hi @Gicehajunior, thank you so much for offering to help maintain MoviePy! Only @Zulko has the necessary permissions to hand out the "Collaborator" role, so I'll leave it to his discretion :) Personally I'm happy to be fairly liberal with permissions.

In the meantime, there's plenty that you can do without push-permissions. If you create pull requests then I can review and merge them (which is what I'd expect to happen even with other maintainers).

https://github.com/Zulko/moviepy/issues/1089#issuecomment-686136473 I mentioned here what my plans are for v2.0, and which bits I think still need assistance (basically anything from https://github.com/Zulko/moviepy/milestone/6, or anything else that takes your fancy!). If you're planning to work on a particular issue, I'd recommend leaving a note on it with your thoughts/plans so that I can keep up-to-date and offer suggestions.

Thanks again!

**Comment by Zulko** [comment]
Thanks for tagging me @tburrows13  and thank you @Gicehajunior for your interest! I am also liberal with granting maintainer access, but it is generally to people who are already contributing to the library, to an extent where not being a maintainer would slow them down. As @tburrows13 mentioned there are also ways to contribute via pull requests that don't require to be a maintainer. Would that work for you? Or do you have other ideas or preferences on how you would like to contribute?

**Comment by tburrows13** [comment]
I'm closing this - @Gicehajunior feel free to reopen if you still want maintainer access after contributing to the project for a bit.
