### ISSUE TITLE
ffmpeg default to auto-detect

### ISSUE THREAD

**Issue by carlodri** [Zulko/moviepy#148]
Hi @Zulko, I wanted to discuss the following idea: I think that the `config_defaults.py` value for `FFMPEG_BINARY` should be `'auto-detect'` by default (not `'ffmpeg-imageio'`), so that `moviepy`, as a first choiche, uses the system's available `ffmpeg`. And in case it doesn't find it, it reverts to (downloading) the `imageio` version.

A simple use-case example: in order to use my preferred, system-wide version of `ffmpeg`, now I am forced to manually change the  `FFMPEG_BINARY` default in the package source (not good practice I think, and not even comfortable...). What do you think? Am I missing some different scenario?

If you like the idea, I can create a pull request.

**Comment by Zulko** [comment]
The reason I force the imageio version of ffmpeg is because Ubuntu/Debian package managers provide completely outdated ffmpeg binaries, which are not compatible with moviepy. With your system, they would need to update ffmpeg, which is a complication.

The second reason is that this way when a beginner reports a bug I am sure that the ffmpeg used is the one of imageio and I know that the ffmpeg version is not the origin of the bug.

**Comment by Zulko** [comment]
Would you like to use ffmpeg 2.6 by the way ? Because in this case we are two, and we could ask for an update of the ffmpeg binaries in imageio at some point.

**Comment by mgaitan** [comment]
what about to have a  `moviepyrc` configuration *alla* matplotlib http://matplotlib.org/users/customizing.html#dynamic-rc-settings ?

this allow have defaults, permanent user overrides in a config file, and dynamic configuration at runtime

**Comment by carlodri** [comment]
@Zulko yes I'm using that version since I need to export in H265 and gif format, it would be nice to get it updated in imageio

@mgaitan that's a good idea!

**Comment by tburrows13** [comment]
This is handled through an environment variable now
