### ISSUE TITLE
TypeError Example LOGO

### ISSUE THREAD

**Issue by excellentiam-prog** [Zulko/moviepy#1507]
Dear, greetings.

I'm using moviepy 1.0.3, it's amazing. 

I tried to create a logo following:
https://github.com/Zulko/moviepy/blob/master/examples/logo.py

But there are several issues. For example, 
1) the variable "screen" is never used
2) 'ImageClip' object has no attribute 'with_mask'
3) the variable "im" in "im.set_pos(2 * ["center"]), shade]" is not defined
4) TypeError "__init__() got an unexpected keyword argument 'is_mask'" in VideoClip(is_mask=True, get_frame=mask_frame)

I would like suggestions, please

**Comment by tburrows13** [comment]
Hello!
The examples are very old as you've observed, they aren't always fully functional. Part of your problem is that they have been changed to work with the current master branch, which renames `set_mask` and `ismask` to `with_mask` and `is_mask`. https://github.com/Zulko/moviepy/blob/21fff157858eee4e9e9b77a73d862f38e520299d/examples/logo.py this links to the example before these changes were made, which will be closer to v1.0.3.

It looks like `im` should be replaced with `screen`.

**Comment by excellentiam-prog** [comment]
@tburrows13  
Thank you very much. You are right, I tried the "im" to "screen", worked.
Still have some issues like "get_frame", I found out that I have to change it to "make_frame". But there are NameError: name 'biGradientScreen' is not definedScreen.

Please, I would like some effect's recommendations to put in a logo. A code example would be very helpful

**Comment by tburrows13** [comment]
Oh `biGradientScreen` seems to be a relic of a very old version of moviepy. It looks like https://zulko.github.io/moviepy/ref/videotools.html#moviepy.video.tools.drawing.color_gradient can do the same thing

**Comment by WilliamPythonDL** [comment]
import numpy as np

from moviepy.editor import *
# import moviepy.video.tools.drawing.color_gradient

w, h = moviesize = (1280, 720)

duration = 1


def f(t, size, a=np.pi / 3, thickness=20):
    w, h = size
    v = thickness * np.array([np.cos(a), np.sin(a)])[::-1]
    center = [int(t * w / duration), h / 2]
    return color_gradient(size, center, v, 0.6, 0.0)


logo = ImageClip("frame.png").resize(width=w / 2).set_mask(mask)

screen = logo.on_color(moviesize, color=(0, 0, 0), pos="center")

shade = ColorClip(moviesize, color=(0, 0, 0))
mask_frame = lambda t: f(t, moviesize, duration)
shade.mask = VideoClip(ismask=True, get_frame=mask_frame)

cc = CompositeVideoClip([screen.set_pos(2 * ["center"]), shade], size=moviesize)

cc.subclip(0, duration).write_videofile("moviepy_logo.avi", fps=24)


NEW ERROR:  
logo = ImageClip("frame.png").resize(width=w / 2).set_mask(mask)
**### NameError: name 'mask' is not defined**

**Comment by tburrows13** [comment]
Try just getting rid of the `.set_mask(mask)`?

**Comment by WilliamPythonDL** [comment]
logo = ImageClip("frame.png").resize(width=w / 2)##.set_mask(mask)

ERROR: 
    shade.mask = VideoClip(ismask=True, get_frame=mask_frame)       
TypeError: __init__() got an unexpected keyword argument 'get_frame'

**Comment by keikoro** [comment]
@WilliamPythonDL It's unclear to me if your issue is related to the original issue by @excellentiam-prog.

I suggest you open a new issue describing your problem in more detail using the issue template. Also, please use GitHub's built-in comment formatting tools so it's easier for us to differentiate any code snippets from regular text, thank you.
