### ISSUE TITLE
Can mac silicon install moviepy?

### ISSUE THREAD

**Issue by bbhxwl** [Zulko/moviepy#1619]
Can mac silicon install moviepy?

**Comment by fjahn** [comment]
Yes, it runs on my M1 just fine. The only thing that does not work is clip.preview (which is only used for debugging anyways), because it requires some features of [pygame](https://github.com/pygame/pygame) that do not work properly yet. See [this issue](https://github.com/pygame/pygame/issues/2452) for details.

**Comment by bbhxwl** [comment]
> Yes, it runs on my M1 just fine. The only thing that does not work is clip.preview (which is only used for debugging anyways), because it requires some features of [pygame](https://github.com/pygame/pygame) that do not work properly yet. See [this issue](https://github.com/pygame/pygame/issues/2452) for details.

How do you install it? Do you use brew?

**Comment by MRROOX** [comment]
brew install ffmpeg

pip3 install moviepy

**Comment by devdevgoat** [comment]
Had to run the following to get it to work on a MacBook Air M1, 13.1 (Ventura):
```fish
$ arch -arm64 brew install ffmpeg
$ pip3 install moviepy
```

Make sure if you're using a virtual env your in the correct shell before running pip3
