### ISSUE TITLE
Additional 5 seconds getting added in video subclip

### ISSUE THREAD

**Issue by teamdaemons** [Zulko/moviepy#1632]
Iam trying to clip a video and save the clipped video. In this case the first 5 seconds of the video. While the video is getting clipped correctly. However the length of the clipped video is still 9 seconds instead of 5 seconds. For some reason an addition 4 seconds keep getting added with no content. Can someone help me with this. I tried to read through various topics on the issue but couldnt figure out.
 
```
# Import everything needed to edit video clips
from moviepy.editor import *
from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip
# loading video dsa gfg intro video
clip = VideoFileClip("file.mp4")

filename = "fileclipped.mp4"
ffmpeg_extract_subclip("file.mp4", 0, 5, targetname=filename)
```

**Comment by karamo-aws** [comment]
@teamdaemons I just tested, and it worked for me. I assume your file.mp4 has something that confuses ffmpeg (unfortunately, this is not terribly uncommon). You might want to try with some other videos, or provide your video here.

Also, it seems you do not need this line, right?
`clip = VideoFileClip("file.mp4")`

**Comment by teamdaemons** [comment]
Thank you so much for responding @karamo-aws The issue replicates for any video I use. if start time is 0 and end time is 5 it works. Just change the starttime to 160 and end time to 170. it will give me a 15 second video instead of expected 10 seconds. Let me know if you are able to spot. I am checking the total duration of the final video in VLC player it plays until 10 secs and the video just closes but the duration shows 15 secs.

**Comment by teamdaemons** [comment]
@karamo-aws did you get a chance to check what I am mentioning?

**Comment by karamo-aws** [comment]
I have verified it happens, but the time it adds varies. I *think* it is because ffmpeg_extract_subclip can only cut at key frames.

I downloaded BigBuckBunny.mp4 (http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4) and looked at its keyframes:
`ffprobe -loglevel error -select_streams v:0 -show_entries packet=pts_time,flags -of csv=print_section=0 BigBuckBunny.mp4 | grep K`

If you vary the times to match the key frames, you will see it finds the first keyframe bigger than t1, and goes until the first keyframe bigger than t2.

You probably don't want to use ffmpeg_extract_subclip, but other functions that cut more precisely, even if it means re-encoding.

**Comment by teamdaemons** [comment]
> times to match the key frames

Thanks for having a quick look. Any suggestions on any other functions that can help achieve the need? I tried to search but somehow this was the one I ended up with.

**Comment by keikoro** [comment]
Closing this issue as it's missing information we request when creating new issues (like specs).

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
