### ISSUE TITLE
abnormal audio playback using AudioFileClip

### ISSUE THREAD

**Issue by clotyxf** [Zulko/moviepy#1710]
```python
import moviepy.editor as mpy

# https://drive.google.com/file/d/1isyI_-aZ62m_dNmHIzrSHam6OlfR2WLD/view?usp=sharing

audio_file = "/tmp/google_tts_audio.mp3"
clip = mpy.AudioFileClip(audio_file)
clip.ipython_display()
```

Use AudioFileClip to read and play, there is a replay problem at the end position.

#### Specifications

  - Python Version:3.8.10
  - Moviepy Version: 1.0.3
  - Platform Name: centos
  - Platform Version: 7

**Comment by keikoro** [comment]
Could you describe the audio problem a bit better? Thanks.

**Comment by clotyxf** [comment]
replay of last word in audio

**Comment by clotyxf** [comment]
When I use AudioFileClip, the audio last word is played repeatedly at the end position.

**Comment by javier2409** [comment]
@clotyxf Did you manage to solve this? I'm having this problem too.

**Comment by jake-nz** [comment]
This problem has been reported many many times.
https://github.com/Zulko/moviepy/issues/1854
https://github.com/Zulko/moviepy/issues/1005
https://github.com/Zulko/moviepy/issues/1717
https://github.com/Zulko/moviepy/issues/1710
https://github.com/Zulko/moviepy/issues/1936

Here's the root cause: https://github.com/Zulko/moviepy/issues/1936#issuecomment-1740785869
