### ISSUE TITLE
does it support m1 mac

### ISSUE THREAD

**Issue by rickstar666** [Zulko/moviepy#1840]
i successed import and run it in my windows pc.
my firends failed. it always says

RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

is it the result of the m1 mac ?

#### Specifications

  - Python Version: 3.10.7
  - Moviepy Version: 1.0.3
  - Platform Name: mac with m1 cpu
  - Platform Version:

**Comment by keikoro** [comment]
How did they install MoviePy on their Mac? Have they tried installing FFMPEG?

**Comment by rickstar666** [comment]
> How did they install MoviePy on their Mac? Have they tried installing FFMPEG?

use codes：
`pip install moviepy`

they have tried
`pip installl ffmpeg`

but it doesnt work. 

all the things i did on my windows is just 
`pip install moviepy`

do they have to do something else ?

**Comment by keikoro** [comment]
Please always provide full error logs (formatted) – in this case, have your friend share them with you, so you can share them here – to help with debugging. Also please complete the specs we ask for (the macOS version your friend is using is missing).

---

Did your friend follow the [install instructions](https://github.com/Zulko/moviepy#installation) in the README? I'll admit the info about the `config_defaults.py` file is confusing as it was removed a while ago, see #1109.

A recent issue [makes reference to an imageio update](https://github.com/Zulko/moviepy/issues/1812) which may have broken the default install method of `ffmpeg` (automatically, while installing `moviepy`). pip installing `ffmpeg` is probably not what you want since that gets you [a different package](https://pypi.org/project/ffmpeg/).

Either way, your friend should be able to install ffmpeg manually/separately via e.g. homebrew: https://formulae.brew.sh/formula/ffmpeg

**Comment by keikoro** [comment]
Well, [this issue comment in imageio-ffmpeg](https://github.com/imageio/imageio-ffmpeg/issues/71#issuecomment-1154046293) makes me think your system is not (yet) supported. The later comments in the thread repeat what I mentioned above (install via homebrew).

If the info here and over there answers your question / helps you solve your problem, please don't forget to close this issue, thanks.

**Comment by rickstar666** [comment]
> Well, [this issue comment in imageio-ffmpeg](https://github.com/imageio/imageio-ffmpeg/issues/71#issuecomment-1154046293) makes me think your system is not (yet) supported. The later comments in the thread repeat what I mentioned above (install via homebrew).
> 
> If the info here and over there answers your question / helps you solve your problem, please don't forget to close this issue, thanks.

ok
