### ISSUE TITLE
ffprobe metadata on video file clips

### ISSUE THREAD

**Issue by thenewguy** [Zulko/moviepy#249]
It would be handy if ffprobe was also wrapped by moviepy.  It would be handy to easily be able to retrieve metadata like overall source bitrate or audio/video stream specific bitrate.  This information is useful when determining how to process the input

-- edit --
Here is a gist I stumbled upon seeing if there was a package put together that already wrapped ffprobe.  It would be pretty easy to handle https://gist.github.com/oldo/dc7ee7f28851922cca09 and fit well with the project I think

**Comment by Zulko** [comment]
I believe that using getting video metadata would be more in the scope of the imageio module (moviepy focuses on get image and sound from clips). Once it is in imageio, it can be easily used in a moviepy script too. @almarklein any thoughts ?

**Comment by almarklein** [comment]
Yes, imageio also supports metadata. We could make it that when the [get_meta_data()](http://imageio.readthedocs.org/en/latest/userapi.html#imageio.core.format.Reader.get_meta_data) is called for the ffmpeg plugin, that we try to call ffprobe. 

@thenewguy would you be interested in making a pull request for this? It should not be too hard; mostly to include that snippet into imageio in a sensible way. Otherwise, please make an issue for a feature request.

**Comment by kerstin** [comment]
I'm closing this issue as it looks like it was agreed a PR would be better suited for other project.

I did a cursory search of [imageio](https://github.com/imageio/imageio)'s issues but didn't see anything that looked like it mirrored this issue. If there was/is and I just overlooked it, please feel free to link it.
