### ISSUE TITLE
Broken Gallery in Documentation

### ISSUE THREAD

**Issue by COLABORATI** [Zulko/moviepy#304]
The [Gallery](http://zulko.github.io/moviepy/gallery.html) page in the docs does not show soem videos, instead it triggers the browser to as to download multiple files, with then can not be downloaded because of a network error. I assume some mime type related webserver configuration error.

**Comment by levimatheri** [comment]
It seems that the rel=0 parameter for youtube url's are being updated or are simply no longer in use. That seems to be the problem: Check out the page source code: http://zulko.github.io/moviepy/_sources/gallery.txt

I searched for the Cup Song Cover Mix edited by this software. I think it's this one:
https://www.youtube.com/watch?v=rIehsqqYFEM
Notice it doesn't have the 'rel' parameter.

**Comment by kerstin** [comment]
The `rel` parameter does not seem to be an issue. It just defines if once the video has stopped playing, related content is shown, see the [Youtube IFrame Player API](https://developers.google.com/youtube/player_parameters#rel).

When I open the gallery, I don't get prompted to download the files but I don't see the videos either. I tried to reproduce the issue and one problem seems to be that the embeds use a deprecated URL scheme ("AS3 player" instead of "IFrame embed", see [this section of the YT docs](https://developers.google.com/youtube/player_parameters#Selecting_Content_to_Play)).

The download prompt seems to be caused by browsing the `http` version of the gallery containing the old URLs. Changing the URLs to `https` and the right scheme seems to make them display both on the secure and the non-secure version of the gallery?

Btw. @levimatheri, I'm not entirely sure about this but thought the moviepy docs are located in the `gh-pages` branch of this repo. (?!)
