### ISSUE TITLE
(optional) Dependencies

### ISSUE THREAD

**Issue by TheChymera** [Zulko/moviepy#311]
How much of moviepy's code is tqdm really needed for?
It seems it only helps to give some very basic visual feedback - so that technically everything in moviepy should be able to work without it. Is that the case?

Is [imageio](http://imageio.github.io/) equivalent to [openimageio](https://sites.google.com/site/openimageio/)?

I'm asking because I am thinking about packaging moviepy for Gentoo - but I would prefer to not have to pull in and maintain another two packages which aren't relevant to any other software.

**Comment by tburrows13** [comment]
I highly doubt that this is relevant now, so I'm closing it.

As far as I can tell imageio is not equivalent to openimageio. Moviepy uses proglog now instead of tqdm, which as well as managing logging output messages and progress bars, it allows for custom callbacks so that the user can hook their own listeners into the output processes.
