### ISSUE TITLE
Possible to create out of bounds subclip

### ISSUE THREAD

**Issue by djh-** [Zulko/moviepy#470]
This reproduces the issue:
```python
#!/usr/bin/python

from moviepy.editor import *


def main():
    # audio clip is 2:20 long (140 seconds)
    audio_clip = AudioFileClip('pull-up-a-chair.mp3')

    # t_end is out of bounds
    subclip = audio_clip.subclip(t_start=130, t_end=150)
    subclip.write_audiofile('render.wav', write_logfile=True)


if __name__ == "__main__":
    main()
```

pull-up-a-chair.mp3 is freely available to download [here](http://us.battle.net/hearthstone/en/media/) at the bottom of the page.

This above errors out with:
`ValueError: zero-size array to reduction operation minimum which has no identity`

This is Python 3.6 with the following libs:
```
appdirs==1.4.2
decorator==4.0.11
imageio==2.1.2
moviepy==0.2.2.13
numpy==1.12.0
olefile==0.44
packaging==16.8
Pillow==4.0.0
pyparsing==2.2.0
six==1.10.0
tqdm==4.11.2
```

Possible fixes include throwing an error when the subclip is created, or replacing t_end with the clip's duration and logging a warning.

I think I prefer the second option, and will happily contribute a fix. Does that seem like the best option?

**Comment by earney** [comment]
The second option sounds good to me also.. Let see what a few other developers think before you create a pull request.

**Comment by Zulko** [comment]
I'd rather avoid changing the ``t_end`` implicitly if a ``t_end`` was specified. Right now ``t_end`` defaults to the clip's duration when no ``t_end`` is provided, and you can always write ``min(t_end, clip.duration)`` to be sure you'll be in the bounds, so you would only provide a specific ``t_end`` if you know it is in the clip's range and you want to be notified otherwise.

As I see it the real problem here is the error thrown, which is very cryptic (it's just Moviepy reading too far in the audio and getting empty data).

**Comment by earney** [comment]
I've added a new pull request #476, which tries to produce a better error message for this case.

**Comment by earney** [comment]
PR request #476 has been merged..  Please open another issue report if you run into this problem again..

**Comment by djh-** [comment]
thanks!

**Comment by gyglim** [comment]
I also have an PR that updates this: https://github.com/Zulko/moviepy/pull/377

I think not throwing an error, if the the frames _should_ be there is the right thing to do. This is what is done for video frames and happens when the duration estimate is wrong.

To summarize, I think this should be the behavior:
1. Accessing an invalid range due as described above, should lead to an exception
2. Accessing frames that are not there, due to a mismatch of the estimated frames based on fps*duration should lead to a warning

Cheers,
Michael
