### ISSUE TITLE
VideoFileClip opens file with wrong width

### ISSUE THREAD

**Issue by reidoda** [Zulko/moviepy#48]
I have a video file that is 426x240, but is opened as 320x240. Is there a way to specify the proper size?

**Comment by davidwdw** [comment]
Hi, I'm having the same issue. It appears that @reidoda 's video is an anamorphic widescreen `[SAR 4:3 DAR 16:9]`, where the sample and display aspect ratios are different. I'm am encountering the same issue with my anamorphic widescreen compressed videos and I did not see an option in the `VideoFileClip` source code an option to resize according to DAR not SAR. Could you reopen this issue and include automatic resizing to DAR instead of SAR? If not, could you recommend how I work with such data? Thanks!
