### ISSUE TITLE
Problem using ffmpeg "minterpolate" to increase framerate

### ISSUE THREAD

**Issue by mmmikael** [Zulko/moviepy#588]
Hey,

I'm trying to increase the frame rate of a video using ffmpeg's [minterpolate](https://ffmpeg.org/ffmpeg-filters.html#minterpolate) with the following line:
```
video.resize(height=size).write_videofile(_tmp_file, codec='libx264', fps=_fps, ffmpeg_params=['-filter', '"minterpolate=\'fps=%d\'"' % _fps])
```
and I am getting this error:
```
MoviePy error: FFMPEG encountered the following error while writing file /tmp/o6qNd6M4y-9y2nAs_720_60.mov:

Filtergraph '"minterpolate='fps=60'"' was defined for audio output stream 0:1 but codec copy was selected.
Filtering and streamcopy cannot be used together.
```
Is there any way to not use `streamcopy`?

**Comment by min050820** [comment]
@mmmikael I am absolutely not related to this project, but let me answer your question. The issue is because you are assigning filter to **both** video and audio, and FFmpeg refuses to apply `minterpolate` filter to audio.

The solution is simply applying filter only to video. You can do it by replacing `-filter` with `-filter:v`. (v means video)
