### ISSUE TITLE
Unable to read grayscale images

### ISSUE THREAD

**Issue by ghotson** [Zulko/moviepy#592]
Error thrown in ImageSequenceClip.py when trying to read from arrays using [:,:,:3] b/c the grayscale images are single channel.

**Comment by keikoro** [comment]
Closing this since it's an old issue with little description and no code samples which could be used to reproduce the problem.

**Comment by lwelzel** [comment]
I can reproduce this issue.
I read some grayscale images from a camera and am trying to produce a video clip from them, also using ImageSequenceClip.

Steps:
1) read in N single channel bitmaps
2) try to create a clip using ImageSequenceClip

#### Expected Behavior
.mp4 is created from the grayscale bitmaps. It doesnt really matter if they are internally converted to multi channel bitmaps.

#### Actual Behavior
Since the image cube does not have an extra dimension for the color channels the indexing in ImageSequenceClip fails:

If with_mask=True
```
  File "...\moviepy\video\io\ImageSequenceClip.py", line 124, in __init__
    if with_mask and (imread(self.sequence[0]).shape[2]==4):
IndexError: tuple index out of range
```
If with_mask=False:
```
  File "...\moviepy\video\io\ImageSequenceClip.py", line 164, in __init__
    self.size = make_frame(0).shape[:2][::-1]
  File "...\moviepy\video\io\ImageSequenceClip.py", line 119, in make_frame
    self.lastimage = imread(self.sequence[index])[:,:,:3] 
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
```
which are two different errors but it seems like they have the same origin, i.e. indexing of the image cubes.

#### Steps to Reproduce the Problem

simplified code:
```
from pathlib import Path
from moviepy.editor import ImageSequenceClip

# get all bitmaps in the sample folder
path = Path("./bmp_sample_dir")
files = path.rglob("*.bmp")
# get the names of the bitmap files as strings
files = [f.as_posix() for f in files]

# create and save the ImageSequenceClip
clip = ImageSequenceClip(files) # <-- this is where the issue happens
clip.write_videofile("sample.mp4")  
```

A sample directory with 5 grayscale bitmaps can be downloaded here: https://drive.google.com/file/d/1NpTPQhupd1L3mzySRQqdvknFKzlJDbAP/view?usp=sharing
Its 5 grayscale (single channel) sample bitmaps. Extract the .7z into the bmp_sample_dir directory and execute the scripts in the same directory as the bmp_sample_dir directory is located.

The issue is not with pathlib, its just used to get the bitmapfiles. When I try the same code using multichannel (RGB) bitmaps it works fine.


#### Specifications

  - Python Version: 3.10
  - Moviepy Version: 1.0.3
  - Platform Name: Windows (also replicated on Fedora 35)
  - Platform Version: 10.0.19044.1706

#### Note
I am not sure if this is rather a feature request than a but but since I found this issue it seemed better to first update this one.
