### ISSUE TITLE
Slow down (or speed up) video gradually

### ISSUE THREAD

**Issue by userlip** [Zulko/moviepy#668]
Hey,

I wanted to ask if it is possible to slow down (and speed up) a Video to a certain factor gradually.

For example if i want to slow down my video to a factor of 0.5 (slow down to half the speed) it is very abrupt if I slow down a clip in the middle of the video.

Id probably have to use
`clip.fl_time( lambda t: t+ math.sin(t), apply_to=['audio'] )`

but I cant figure out how to use a factor in that line of code (0.5 for half speed and 2 for double speed for example)

Thanks

**Comment by Zulko** [comment]
Good question, and that's not a trivial problem at all. The simplest solution is this:

Say you want to change the speed factor between 1 and X from times t1 to t2 of your original speed.
- Cut your clip into subclips: one for ``[0 t1]``, one for ``[t2 end]``, and 5 little clips between ``[t1 t2]``. The little clips receive ``speedx(x)`` with x going slowly between 1 and x, and clip ``[t2 end]`` gets ``speedx(X)``.

There are other, more exact, and more difficult solutions:

1- trace the desired speed profile, compute it's integral, and feed it to ``fl_time``. This is tricky because (1) you need to make some integral computations and (2) you need to compute the final duration of the clip by hand.

2- trace a profile of the time, a function f(original_time) => new_time, using linear chunks, then smooth this function using ``g(t) => (f(t-1) + f(t+1))/2`` and feed ``g`` to ``fl_time``. (I can give you more details but that's also difficult to do by hand).

**Comment by userlip** [comment]
Thanks for the answer im going to try it out and provide feedback!

**Comment by keikoro** [comment]
@userlip Any update on this, can we close the issue?

**Comment by userlip** [comment]
The result obviously got better the smaller the clips where we cut out.
Still a pain to implement :)
