### ISSUE TITLE
Extracting frames

### ISSUE THREAD

**Issue by srikanthsridar** [Zulko/moviepy#702]
Is there a way to extract frames in jpg to python numpy?

**Comment by Zulko** [comment]
No clear what you mean by "frames in jpg to python numpy.
Here are some examples of code in case it helps:

```python
import moviepy.editor as mpe
video = mpe.VideoFileClip('some_video.mp4')
np_frame = video.get_frame(2) # get the frame at t=2 seconds
np_frame = video.get_frame(frame_number * video_fps) # get frame by index
video.save_frame('my_image.jpeg', t=2) # save frame at t=2 as JPEG
```

**Comment by srikanthsridar** [comment]
Hey zulko,

Thank you for quick reply.I meant i have a video from which i need to extract frames at a particular FPS.But  conditions are the image format is jpg and a certain quality like "qscale:v" parameter in ffmpeg and i need the extracted images(frames) in numpy

**Comment by Zulko** [comment]
You can do it in moviepy with:
```python
my_numpy_array = mpe.ImageClip('my_image.jpeg').get_frame() 
```
But there are many more libraries that can do that such as Pillow, certainly Scipy, etc.

**Comment by srikanthsridar** [comment]
Yes in many other libraries including the ones you mentioned, the issue is ffmpeg extracts the frames for a certain size(file size).When I load the "ffmpeg extracted" image using (say) OpenCV's imread the size in memory is increased.My application requires thousands of images to be loaded in memory.So an 100MB files in harddisk increases to 2GB in RAM.any thoughts on this direction ?

**Comment by Zulko** [comment]
can you explain what is the end goal of your project ? image analysis ? making a video ?

**Comment by srikanthsridar** [comment]
It is image analysis from a video.

14400 files taking 92MB disk space
14400 files in python list takes 2 to 2.5GB in RAM

**Comment by Zulko** [comment]
I will close this as it is not Moviepy related anymore. For this kind of support (which is not a) it is better to post to Stackoverflow or Reddit/Moviepy, we try to keep this section for bug reports or feature requests.

You should give more details when you post on these sites, such as what kind of analysis you are doing. The key question here is - are you really obliged to open all the images at the same time ?

**Comment by srikanthsridar** [comment]
Sure,I understand what you are saying.will think about the approach.Between the point am trying to make is opencv or scipy when decoding the image (extracted from ffmpeg) the file size changes.Thank you for such a quick response.

**Comment by davidbernat** [comment]
Hello @Zulko. Asking to reopen this ticket for its generic title. I am noticing that `get_frame` appears to be of fixed speed for successive calls; i.e., ten calls appears to take up to one second or more to process. This is presumably because the `VideoFileClip` object does not store video data in memory, and therefore must reload the entire clip, again, on each successive call. Is this correct, and is there a faster alternative? Would you be available to discuss this offline in email?

**Comment by keikoro** [comment]
@davidbernat It'd be better to open a new issue for this than for us to reopen this very old one, especially since nothing in OP's original question suggests it had anything to do with what you are asking here.

Subject lines aren't necessarily good indicators for if older issues match what you're looking for, and we don't want to make anyone, including ourselves, waste time by reading through years-old threads only to discover they are of little relevance to what's being asked now.

**Comment by davidbernat** [comment]
@keikoro It was the closest one that matched the search; paradoxically GitHub search has internal thresholds that bias search, including code from older than a year ago, so I am as surprised as you. As for `make_frames` I implemented my own solution offline and contribute here for the benefit of others who Google search, which, also is where I first arrived at this ticket, in addition to Github search. As for implementation, when we pivot the discussion from documentation to optimization (as Osa and I were discussing), then revisiting this issue will be beneficial. There are improvements to be made, after the community moves more towards implementation maintainers, which is why we were talking baseline end of 2024. There is no reason for my repositories to be public though I still spend twenty hours a week on code and have for ten years, like you. (And now I have committed the cardinal sin of cross-posting commentary across GitHub issues. Ping me when you need me. Thanks. xo)
