### ISSUE TITLE
inconsistent behaviour of clip.get_frame()

### ISSUE THREAD

**Issue by TejasBob** [Zulko/moviepy#751]
I'm trying following script in ipython terminal.

```
from moviepy.editor import *

clip = VideoFileClip(file_path, has_mask=True)
print(clip.duration) # 6.04
img = clip.get_frame(9)
```

This results in 

> OSError: MoviePy error: failed to read the first frame of video file file_path ...

but when I do
```
img = clip.get_frame(6)
img = clip.get_frame(9)
```
it doesn't fail. Instead it gives warning 

> ... bytes wanted but 0 bytes read,at frame 225/152, at time 9.00/6.04 sec. Using the last valid frame instead.

**Comment by GarciaDelMolino** [comment]
when `get_frame` fails to read the requested frame, it returns "the last valid frame instead." If there is no previous frame, then it returns `OSError`. [Check the source here.](https://github.com/Zulko/moviepy/blob/a002df34a1b974e73cbea02c2f436c94b81fbc39/moviepy/video/io/ffmpeg_reader.py#L116)

In your case, you request the frame at time 9 seconds, which doesn't exist. If you have not requested any frame before (1st example), `clip.get_frame` will give an error. Otherwise (2nd example), a warning, returning the frame at time 6 seconds.

**Comment by TejasBob** [comment]
got it.

**Comment by keikoro** [comment]
@TejasBob It sounds like the above comment helped solve the problem, I'm thus closing this issue. Please reopen if the problem persists.
