### ISSUE TITLE
ffmpeg_reader is creating zombie processes

### ISSUE THREAD

**Issue by Aran-Fey** [Zulko/moviepy#833]
Opening a video file and deleting the variable leaves a zombie ffmpeg process running in the background. Steps to reproduce:

```python
from moviepy.editor import VideoFileClip
import subprocess, gc

clip = VideoFileClip(PATH_TO_SOME_VIDEO)

del clip
gc.collect()

print([proc.args for proc in subprocess._active])
subprocess.run('echo hi', shell=True)
```

Output:
```
[['C:\\Users\\Rawing\\AppData\\Local\\imageio\\ffmpeg\\ffmpeg-win32-v3.2.4.exe',
 '-i', 'D:\\users\\aran-fey\\desktop\\temp {e}\\SV card videos\\101221050 Navy L
ieutenant.mkv', '-loglevel', 'error', '-f', 'image2pipe', '-vf', 'scale=959:1484
', '-sws_flags', 'bicubic', '-pix_fmt', 'rgb24', '-vcodec', 'rawvideo', '-']]
Traceback (most recent call last):
  File "temp.py", line 14, in <module>
    subprocess.run('echo hi', shell=True)
  File "C:\Python37\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python37\lib\subprocess.py", line 645, in __init__
    _cleanup()
  File "C:\Python37\lib\subprocess.py", line 215, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
  File "C:\Python37\lib\subprocess.py", line 1193, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] The handle is invalid
```

As you can see, a ffmpeg process is running. The `subprocess` module tries to clean it up, but fails. Evidently, this ffmpeg process is spawned by the [`FFMPEG_VideoReader` class](https://github.com/Zulko/moviepy/blob/master/moviepy/video/io/ffmpeg_reader.py#L23), as [the arguments match perfectly](https://github.com/Zulko/moviepy/blob/master/moviepy/video/io/ffmpeg_reader.py#L89-L95).

Related issues: #677 #569

**Comment by Aran-Fey** [comment]
Turns out adding `clip.close()` solves the problem. Which begs the question: Why do [none](https://github.com/Zulko/moviepy#example) [of](http://zulko.github.io/moviepy/getting_started/quick_presentation.html#example-code) [these](http://zulko.github.io/moviepy/getting_started/videoclips.html?highlight=videofileclip#videofileclip) code examples call `close()`?

**Comment by jamesneo3000** [comment]
same issue

**Comment by Julian-O** [comment]
> Why do [none] [of] [these] code examples call `close()`?

The answer isn't very pretty.

I introduced the `close()` functionality fairly recently in the history of MoviePy. The main purpose was to address the zombie process issue above, which *only* affects Windows and only then in limited circumstances.

So the code examples don't include it because (a) it is still new and they haven't been updated, (b) because it isn't necessary for most (non-Windows) users, (c) even on Windows machines these particular examples will run fine.

If the goal of the example is to get people started quickly, it could be argued that they should be left alone. If the goal is to encourage people to write portable, robust software with MoviePy, they should be updated to use `close()`. (Actually, I prefer to use a context manager so the scope is beyond doubt.)

**Comment by emads3** [comment]
I have the same issue

**Comment by arianaa30** [comment]
I have same issue (Windows). In my for loop, I close each clip. Now instead of index #2, I get the problem for index 4!

```
            c.reader.close()
            c.audio.reader.close_proc()
```

**Comment by Julian-O** [comment]
@arianaa30: I am travelling with only a phone at the moment, so this is just a quick reaction rather than a careful response:

Replace the last two lines with 'c.close()'

**Comment by arianaa30** [comment]
Thanks for the hint. I did, but still randomly get the same error.

**Comment by Julian-O** [comment]
I've taken a slightly closer look now, but remain confused.

I do wonder if there is something in `#do something` that is creating a new clip that isn't being closed, but only because I am clutching at straws.

It would be interesting to know if `os.remove(filename)` succeeds after the `close()` calls. (Obviously, back up any media you care about first.) It should. If it doesn't, there is a zombie process blocking it.

**Comment by Julian-O** [comment]
I would also recommend using a context manager to ensure everything is cleaned up, even if exceptions get raised:

    with VideoFileClip(filename) as c:
        duration = c.duration
        print(str(duration))
        if int(duration) > float(length/parts):
             #do something

**Comment by arianaa30** [comment]
Yeah I transferred the code to Ubuntu, and it runs there with no issues. But will continue discovering on Windows and let you know. Thanks.

**Comment by keikoro** [comment]
Closing this since suggestions for dealing with the issue were provided.

Feel free to open a new issue following the issue template and referencing this older issue if the problem reoccurs.
