### ISSUE TITLE
Hang after creating 126 VideoFileClips (MacOS)

### ISSUE THREAD

**Issue by markusloffler** [Zulko/moviepy#992]
### Expected Behavior
Constructing a VideoFileClip() does not hang

### Actual Behavior
Constructing a VideoFileClip() hangs after 126 VideoFileClips have been created
Specifically, ffmpeg_reader.py / ffmpeg_read_image / proc.stdout.readline() never returns
The activity monitor shows that for each instance of VideoFileClip, a subprocess is created and kept

### Steps to Reproduce the Problem
Create 126 VideoFileClip objects and store them into an array (for concatenation)

### Specifications
  - Python Version: 3.6.5
  - Moviepy Version: 1.0.0
  - Platform Name: MacOS
  - Platform Version: 10.14.5

**Comment by markusloffler** [comment]
Each VideoFileClip() also creates an AudioFileClip(), which calls Popen(). So there must be a limit of 256 subprocesses or so

**Comment by markusloffler** [comment]
Maximum number of open files is set to 256, raising it higher did not help:
resource.setrlimit(resource.RLIMIT_NOFILE, (1000, 1000))

**Comment by kyb3r** [comment]
same issue with me, what I did to try to solve it was load files into memory instead of keeping it opened

**Comment by keikoro** [comment]
Closing this issue as it's older and based on an older MoviePy version, so impossible to tell if it's still relevant. Also, a suggestion on how to circumenvent the issue was posted above.

Do report back – following our issue template – if the problem persists when you try with the latest master (not the last PyPI release).
